todoist/models.py
from . import db
from datetime import datetime
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    '''flask-login 必需的回调函数，从数据库中通过id找到用户'''
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    projects = db.relationship('Project', backref='user')
    tasks = db.relationship('Task', backref='user', lazy='dynamic')
    logs = db.relationship('UserLog', backref='user')
    titles = db.relationship('Titles', backref='user')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True


class Project(db.Model):
    __tablename__ = 'projects'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    name = db.Column(db.String(64), index=True)
    icon = db.Column(db.String(64), default='file')
    tasks = db.relationship('Task', backref='project_task')

    def default_project(user):
        projects = [['个人', 'user'], ['工作', 'paperclip'], [
            '购物', 'shopping-cart'], ['饮食', 'cutlery'], ['杂项', 'certificate']]
        for p in projects:
            project = Project(name=p[0], user_id=user.id, icon=p[1])
            db.session.add(project)


class Task(db.Model):
    __tablename__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    task = db.Column(db.String(64), index=True)
    timestamp = db.Column(db.DateTime, default=datetime.now)
    timenode = db.Column(db.String(64), index=True)
    priority = db.Column(db.Integer, index=True, default=1)
    project = db.Column(db.String(64), db.ForeignKey('projects.name'))
    filish = db.Column(db.Boolean, default=False)
    title = db.Column(db.Integer, db.ForeignKey('titles.id'))


class Titles(db.Model):
    __tablename__ = 'titles'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    title = db.Column(db.String(64), index=True)
    tasks = db.relationship('Task', backref='tasks')


class UserLog(db.Model):
    __tablename__ = 'userlogs'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    log = db.Column(db.String(128))
    timestamp = db.Column(db.DateTime, default=datetime.now)

todoist/main/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, BooleanField, SelectField, DateTimeField, DateField
from wtforms.validators import Required, Length, Optional
from flask_login import current_user
from datetime import datetime


class AddProject(FlaskForm):
    name = StringField('项目名：', validators=[Required(), Length(1, 64)])
    submit = SubmitField('保存')


class AddTask(FlaskForm):
    task = StringField('任务：', validators=[Required(), Length(1, 64)])
    title = SelectField('标签：', render_kw={"style": "width:20%;"})
    new_title = StringField('新标签：', validators=[Optional(), Length(
        1, 32)], render_kw={"style": "width:20%;"})
    project = SelectField('项目:', render_kw={"style": "width:20%;"})
    timenode = StringField('时间节点：', render_kw={
                           "style": "width:20%;"}, default=datetime.now().strftime("%Y-%m-%d"))
    priority = SelectField(
        '优先级：', choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], render_kw={"style": "width:20%;"})
    submit = SubmitField('保存')

    def __init__(self, *args, **kwargs):
        super(AddTask, self).__init__(*args, **kwargs)
        self.project.choices = [(p.name, p.name)
                                for p in current_user.projects]
        self.title.choices = [(t.id, t.title)
                              for t in current_user.titles]


class Search(FlaskForm):
    s = StringField('', validators=[Required(),
                                    Length(1, 64)], id="search")
    search = SubmitField('提交')

todoist/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, ValidationError, BooleanField
from wtforms.validators import Required, Length, Email, EqualTo, Regexp
from wtforms import ValidationError
from ..models import User


class UserRegister(FlaskForm):
    username = StringField('用户名：', validators=[Required(), Length(1, 64), Regexp(
        '^[A-Za-z][A-Za-z0-9]*$', 0, 'Usernames must have only letters,numbers,')])
    email = StringField('邮箱：', validators=[Required(), Email()])
    password = PasswordField(
        '密码：', validators=[Required(), EqualTo('password2', message='两次密码输入不一致')])
    password2 = PasswordField('确认密码：', validators=[Required()])
    submit = SubmitField('马上注册')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('此邮箱已注册')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已存在')


class UserLogin(FlaskForm):
    username = StringField('', validators=[Required(), Length(1, 64), Regexp(
        '^[A-Za-z][A-Za-z0-9]*$', 0, 'Usernames must have only letters,numbers,')])
    password = PasswordField('', validators=[Required()])
    submit = SubmitField('登录')

todoist/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config
import pymysql
pymysql.install_as_MySQLdb()

bootstrap = Bootstrap()
mail = Mail()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'user.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main
    app.register_blueprint(main)
    from .user import user
    app.register_blueprint(user, url_prefix='/user')

    return app

todoist/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

todoist/main/views.py
from flask import render_template, session, redirect, url_for, request, abort, make_response
from datetime import datetime, timezone, timedelta
from flask_login import login_required, current_user
from .forms import AddProject, AddTask, Search

from . import main
from .. import db
from ..models import User, Project, Task, Titles
from sqlalchemy import and_, or_
from collections import OrderedDict


@main.before_request
def main_form():
    if current_user.is_authenticated:
        projectform = AddProject()
        if projectform.validate_on_submit():
            p = Project(name=projectform.name.data, user_id=current_user.id)
            db.session.add(p)
            return redirect(url_for('.index'))


@main.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    search = Search()
    edit_task_form = AddTask()
    projectform = AddProject()
    if not search.s.data:
        return redirect(url_for('.index'))
    key = '%' + search.s.data + '%'
    tasks = Task.query.filter(Task.task.like(key)).all()
    return render_template('tasks-from-project.html', tasks=tasks, key=search.s.data, search=search,
                           edit_task_form=edit_task_form, projectform=projectform)


@main.route('/add-task', methods=['GET', 'POST'])
@login_required
def add_task():
    edit_task_form = AddTask()
    if edit_task_form.validate_on_submit():
        t = Task(task=taskform.task.data, project=taskform.project.data,
                 timenode=taskform.timenode.data, user_id=current_user.id)
        if taskform.new_title.data:
            nt = Titles(title=taskform.new_title.data,
                        user_id=current_user.id)
            db.session.add(nt)
            db.session.commit()
            t.title = nt.id
            db.session.add(t)
        else:
            t.title = taskform.new_title.data
            db.session.add(t)
        return redirect(request.referrer)


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    now = datetime.now()
    search = Search()
    edit_task_form = AddTask()
    projectform = AddProject()
    today_tasks = current_user.tasks.filter(
        Task.timenode == datetime.now().strftime("%Y-%m-%d")).all()
    overdue_tasks = current_user.tasks.filter(and_(Task.filish == False,
                                                   Task.timenode < datetime.now().strftime("%Y-%m-%d"))).all()
    return render_template('today.html', now=now, search=search, today_tasks=today_tasks, edit_task_form=edit_task_form,
                           projectform=projectform, overdue_tasks=overdue_tasks)


@main.route('/sevenday', methods=['GET', 'POST'])
@login_required
def sevenday():
    search = Search()
    edit_task_form = AddTask()
    projectform = AddProject()
    days = []
    for i in range(7):
        days.append((datetime.now() + timedelta(days=i)
                     ).strftime("%Y-%m-%d"))
    tasks7 = OrderedDict()
    for day in days:
        tasks7[day] = []
        for task in current_user.tasks.all():
            if task.timenode == day:
                tasks7[day].append(task)
    return render_template('seven-day.html', search=search, tasks7=tasks7, edit_task_form=edit_task_form,
                           projectform=projectform)


@main.route('/task/filish/<int:id>')
@login_required
def task_filish(id):
    task = Task.query.get_or_404(id)
    task.filish = True
    db.session.add(task)
    return redirect(request.referrer)


@main.route('/task/unfilish/<int:id>')
@login_required
def task_unfilish(id):
    task = Task.query.get_or_404(id)
    task.filish = False
    db.session.add(task)
    return redirect(request.referrer)


@main.route('/task/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_task(id):
    task = Task.query.get_or_404(id)
    if request.method == 'GET':
        return redirect(url_for('.index'))
    if request.method == 'POST':
        task.task = request.form.get('task_task' + str(id))
        if request.form.get('project' + str(id)):
            task.project = request.form.get('project' + str(id))
        task.timenode = request.form.get('timenode' + str(id))
        task.priority = request.form.get('priority' + str(id))
        db.session.add(task)
    return redirect(request.referrer)


@main.route('/project/<project>', methods=['GET', 'POST'])
@login_required
def project(project):
    p = Project.query.filter_by(name=project).all()
    if not p:
        abort(404)
    tasks = Task.query.filter_by(
        project=project).filter_by(filish=False).all()
    edit_task_form = AddTask()
    projectform = AddProject()
    search = Search()
    return render_template('tasks-from-project.html', search=search, edit_task_form=edit_task_form,
                           projectform=projectform, tasks=tasks, project=project, page_p=project)


@main.route('/title')
@login_required
def show_title():
    resp = make_response(redirect(request.referrer))
    resp.set_cookie('show_what', 'title', max_age=60 * 60 * 24 * 30)
    return resp


@main.route('/project')
@login_required
def show_project():
    resp = make_response(redirect(request.referrer))
    resp.set_cookie('show_what', 'project', max_age=60 * 60 * 24 * 30)
    return resp


@main.route('/title/<title>', methods=['GET', 'POST'])
@login_required
def title(title):
    t = Titles.query.filter_by(title=title).first()
    if not t:
        abort(404)
    tasks = Task.query.filter_by(title=t.id).filter_by(filish=False).all()
    edit_task_form = AddTask()
    projectform = AddProject()
    search = Search()
    return render_template('tasks-from-project.html', search=search, tasks=tasks, edit_task_form=edit_task_form,
                           projectform=projectform, title=title)

todoist/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

todoist/user/views.py
from flask import render_template, redirect, url_for, abort, flash, request, current_app
from . import user
from .forms import UserRegister, UserLogin
from ..main.forms import AddProject
from ..models import User, Project
from .. import db
from flask_login import login_user, logout_user, login_required, current_user
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from ..email import send_email


@user.before_app_request
def before_request():
    if current_user.is_authenticated and not current_user.confirmed and request.endpoint[:5] != 'user.' and request.endpoint != 'static':
        return redirect(url_for('user.unconfirmed'))


@user.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('main.index'))
    return render_template('user/unconfirmed.html')


@user.route('/register', methods=['GET', 'POST'])
def register():
    form = UserRegister()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=form.password.data, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        send_email(to=user.email, subject='请验证您的邮箱',
                   template='confirm', user=user, token=token)
        Project.default_project(user)
        flash('注册成功')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = UserLogin()
    projectform = AddProject()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user, True)
            flash('登录成功')
            return redirect(request.args.get('next') or url_for('main.index'))
        flash('帐号/密码不正确')
        return redirect(url_for('.login'))
    return render_template('user/login.html', form=form, projectform=projectform)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('你已登出')
    return redirect(url_for('.login'))


@user.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    if current_user.confirm(token):
        flash('您的邮箱验证通过，谢谢！')
    else:
        flash('请检查链接有效，并且没有过期。')
    return redirect(url_for('main.index'))


@user.route('/confirm')
@login_required
def resend_email():
    token = current_user.generate_confirmation_token()
    send_email(to=current_user.email, subject='请验证您的邮箱',
               template='confirm', user=current_user, token=token)
    flash('一封新的账户验证邮件已发送到您的邮箱，请注意查收。')
    return redirect(url_for('main.index'))

todoist/templates/add_project.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block right %}
<div class="form" id="register">
<h1 class="text-center" style="color: #fff;">添加项目</h1>
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

todoist/templates/base.html
{% import "bootstrap/wtf.html" as wtf %}
<!DOCTYPE html>
<html>

<head>
    <title>MyTodoist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 引入 Bootstrap -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/square/red.css') }}" rel="stylesheet">
    <!-- <link href="{{ url_for('static',filename='css/polaris/polaris.css') }}" rel="stylesheet"> -->
    <link href="{{ url_for('static',filename='css/main.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/moment-with-locales.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/icheck.js') }}"></script>
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container col-lg-8 col-lg-offset-2 col-sm-12">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MyTodoist</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a data-toggle="modal" href="#add-task"><span class="glyphicon glyphicon-plus"></span></a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-bell"></span></a></li>
                </ul>
                <div class="navbar-form navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                  开始
                                  <b class="caret"></b>
                              </a> {% if current_user.is_authenticated %}
                            <ul class="dropdown-menu">
                                <li><a href="#">个人中心</a></li>
                                <li><a href="#">查看活动日志</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                                <li><a href="#">设置</a></li>
                            </ul>
                            {% else %}
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('user.register') }}">注册</a></li>
                                <li><a href="#">找回密码</a></li>
                                <li class="divider"></li>
                                <li><a href="{{ url_for('user.login') }}">登录</a></li>
                                <li><a href="#">设置</a></li>
                            </ul>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="navbar-form navbar-right" role="search">
                    <form class="navbar-form navbar-right" action="{{ url_for('main.search') }}" role="search" method="post">
                        {{ search.csrf_token }}
                        <div class="form-group">
                            {{ search.s.label }} {{ search.s(id="search",class ="form-control",placeholder = "请输入关键字")}}
                        </div>
                        <button type="submit" id="search" class="btn btn-default">搜索</button>
                    </form>
                </div>
                <!--  <script>
                    document.getElementById("search").style.display="none";
                    document.onkeydown = function(){
                        if(event.keyCode==13)
                        {
                            document.getElementById("search").click();   
                        }
                    };
                    </script> -->
            </div>
        </div>
        <!--end nav container-->
    </nav>
    {% endblock %}
    <div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %} {% block page_content %}{% endblock %}
    </div>
    {% block body %} {% block leftnav %}
    <div class="right-navbar col-lg-2 col-lg-offset-2 col-xs-4">
        <ul class="nav nav-pills nav-stacked" style="padding-top: 20px;">
            <li><a href="/"><span class="glyphicon glyphicon-tasks"></span> 今天</a></li>
            <li><a href="{{ url_for('main.sevenday') }}"><span class="glyphicon glyphicon-list-alt"></span> 接下来7天</a></li>
        </ul>
        <ul class="nav nav-tabs" style="padding-top: 20px;">
            <li {% if request.cookies.get( "show_what")=="project" %} class="active" {% endif %}><a href="{{ url_for('main.show_project') }}">项目</a></li>
            <li {% if request.cookies.get( "show_what")=="title" %} class="active" {% endif %}><a href="{{ url_for('main.show_title') }}">标签</a></li>
            <!-- <li><a href="#">过滤器</a></li> -->
        </ul>
        {% if request.cookies.get("show_what")=="project" %}
        <ul class="nav nav-pills nav-stacked" style="padding-top: 5px;">
            {% for p in current_user.projects %}
            <li {% if page_p==p.name %}class="active" {% endif %}><a href="{{ url_for('main.project',project=p.name) }}"><span class="glyphicon glyphicon-{{ p.icon }}"> </span> {{ p.name }}</a></li>
            {% endfor %}
            <li class="divider" style="color: #fff;"></li>
            <li><a data-toggle="modal" href="#add-project" style="color: red;"><span class="glyphicon glyphicon-plus"></span> 添加项目</a></li>
        </ul>
        {% elif request.cookies.get("show_what")=="title" %}
        <div class="title" style="padding-top: 10px;">
            {% for t in current_user.titles %}
            <a href="{{ url_for('main.title',title=t.title) }}">
                <button type="button" class="btn btn-default btn-sm">{{ t.title }}</button>
            </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endblock %}
    <div class="right-navbar col-lg-6 col-xs-8">
        {% block right %} {% endblock right %}
    </div>
    {% endblock %} {% block modal %}
    <!-- 模态框（Modal） -->
    <div class="modal fade" id="add-project" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">添加项目</h4>
                </div>
                <div class="modal-body">
                    {{ wtf.quick_form(projectform) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    {% if current_user.is_authenticated %}
                    <button type="submit" class="btn btn-primary" onclick="load()">提交</button>
                    <script>
                    function load() {
                        document.getElementById("submit").click();
                    }
                    document.getElementById("submit").style.display = "none"
                    </script>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="add-task" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">添加任务</h4>
                </div>
                <div class="modal-body">
                    <form role="form" action="{{ url_for('main.add_task') }}" method="post">
                        {{ edit_task_form.csrf_token }}
                        <div class="form-group">
                            {{ edit_task_form.task.label }} {{ edit_task_form.task(id="task",class ="form-control")}}
                        </div>
                        <div class="form-group">
                            {{ edit_task_form.project.label }} {{ edit_task_form.project(id="project",class ="form-control")}}
                        </div>
                        <div class="form-group">
                            {{ edit_task_form.title.label }} {{ edit_task_form.title(id="title",class ="form-control")}}
                        </div>
                        <div class="form-group">
                            {{ edit_task_form.new_title.label }} {{ edit_task_form.new_title(id="new_title",class ="form-control")}}
                        </div>
                        <div class="form-group">
                            {{ edit_task_form.timenode.label }} {{ edit_task_form.timenode(id="add-timenode",class ="form-control")}}
                        </div>
                        <div class="form-group">
                            {{ edit_task_form.priority.label }} {{ edit_task_form.priority(id="priority",class ="form-control")}}
                        </div>
                        <button type="submit" class="btn btn-default" id="submit-add-task">提交</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    {% if current_user.is_authenticated %}
                    <button type="submit" class="btn btn-primary" id="newtask">提交</button>
                    <script>
                    // function task() {
                    //     document.getElementById("tasksave").click();
                    // }
                    $("#newtask").on("click", function() {
                        document.getElementById("submit-add-task").click();
                    });
                    document.getElementById("submit-add-task").style.display = "none";
                    // document.getElementById("timenode").type="date";
                    $("#add-timenode").datetimepicker({ format: 'yyyy-mm-dd' });
                    </script>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

todoist/templates/seven-day.html
{% extends "base.html" %} {% block right %} {% for task in tasks7 %}
<div class="task-day">
    <h2><p><small> 
  <script>
  var time = moment('{{ task }}').locale('zh-cn').format('dddd MMMDo'); 
  document.write(time);
  </script>         
</small></p></h2> {% if tasks7[task] %} {% set tasks=tasks7[task] %} {% include 'task-list.html' %} {% endif %}
</div>
<div class="add-task" style="padding-bttom: 30px;">
    <a data-toggle="modal" href="#add-task" style="color: red;"><span class="glyphicon glyphicon-plus"></span> 添加任务</a>
</div>
{% endfor %} {% endblock right %}

todoist/templates/tasks-from-project.html
{% extends "base.html" %} {% block right %}
    <div class="ot-tasks">
        <h3>
            <p style="color: red;">{% if project %}<span class="glyphicon glyphicon-file"></span>
                {{ project }}{% elif title %}<span class="glyphicon glyphicon-pushpin"></span> {{ title }}{% elif key %}
                <span class="glyphicon glyphicon-search"></span> {{ key }}{% endif %}
                <small> 未完成的任务</small>
            </p>
        </h3>
        {% include 'task-list.html' %}
    </div>
{% endblock %}

todoist/templates/today.html
{% extends "base.html" %} {% block right %} {% if overdue_tasks !=[] %}
<div class="ot-tasks">
    <h3><p style="color: red;">有过期的任务</p></h3> {% set tasks=overdue_tasks %} {% include 'task-list.html' %}
</div>
{% endif %}
<div class="today-tasks">
    <h2><p>今天 <small> 
  <script>
  var time = moment('{{ now }}').locale('zh-cn').format('dddd MMMDo'); 
  document.write(time);
  </script>         
</small></p></h2> {% set tasks=today_tasks %} {% include 'task-list.html' %}
    <a data-toggle="modal" href="#add-task" style="color: red;"><span class="glyphicon glyphicon-plus"></span> 添加任务</a>
</div>
{% endblock right %}